name: Check Source
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for valid branches
      run: |
        if [[ ${{github.head_ref}} != release* && ${{github.head_ref}} != hotfix* ]]; then
          echo "This pull request can only be merged into the master branch from either the hotfix or release branch."
          exit 1
        fi
